services:
  # Backend service
  - type: web
    name: email-filter-backend
    env: node
    root: BACKEND
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: PORT
        value: 8081
      - key: NODE_ENV
        value: production

  # Frontend service
  - type: web
    name: email-filter-frontend
    env: node
    root: frontend
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://email-filter-backend.onrender.com
      - key: NODE_ENV
        value: production 